### ISSUE TITLE
[Bug] Error with JEIPlugin

### ISSUE THREAD

**Issue by Xyphenore** [iglee42/CreateCasing#40]
**Describe the bug**

When create a world, the JEIPlugin for the mod raised an error to console, about the ItemStack value.

Error from console:
'Caught an error from mod plugin: class fr.iglee42.createcasing.compat.jei.JEIPlugin createcasing:jei
java.lang.IllegalArgumentException: ItemStack value must not be empty. 0 air minecraft:air'

**To Reproduce**

- Install the mod.
- Run the game with the output console.
- Create a world
- Error is printed to console.

**Expected behavior**

No error.

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - Minecraft Version: 1.20.1
 - Forge Version: 47.1.47
 - Mod Version: 1.4.2
 - Create Version: 0.5.1d
 - JEI Version: 15.2.0.27

**Additional context**

Traceback:
```
Caught an error from mod plugin: class fr.iglee42.createcasing.compat.jei.JEIPlugin createcasing:jei
java.lang.IllegalArgumentException: ItemStack value must not be empty. 0 air minecraft:air
	at TRANSFORMER/jei@15.2.0.27/mezz.jei.common.util.ErrorUtil.checkNotEmpty(ErrorUtil.java:76)
	at TRANSFORMER/jei@15.2.0.27/mezz.jei.library.plugins.vanilla.ingredients.ItemStackHelper.getUniqueId(ItemStackHelper.java:51)
	at TRANSFORMER/jei@15.2.0.27/mezz.jei.library.plugins.vanilla.ingredients.ItemStackHelper.getUniqueId(ItemStackHelper.java:27)
	at TRANSFORMER/jei@15.2.0.27/mezz.jei.library.ingredients.IngredientSet.lambda$create$0(IngredientSet.java:17)
	at TRANSFORMER/jei@15.2.0.27/mezz.jei.library.ingredients.IngredientSet.remove(IngredientSet.java:38)
	at TRANSFORMER/jei@15.2.0.27/mezz.jei.library.ingredients.IngredientSet.removeAll(IngredientSet.java:50)
	at TRANSFORMER/jei@15.2.0.27/mezz.jei.library.ingredients.IngredientInfo.removeIngredients(IngredientInfo.java:51)
	at TRANSFORMER/jei@15.2.0.27/mezz.jei.library.ingredients.IngredientManager.removeIngredientsAtRuntime(IngredientManager.java:131)
	at TRANSFORMER/createcasing@1.20.1-1.4.2/fr.iglee42.createcasing.compat.jei.JEIPlugin.registerRecipes(JEIPlugin.java:28)
	at TRANSFORMER/jei@15.2.0.27/mezz.jei.library.load.PluginLoader.lambda$createRecipeManager$10(PluginLoader.java:144)
	at TRANSFORMER/jei@15.2.0.27/mezz.jei.library.load.PluginCaller.callOnPlugins(PluginCaller.java:27)
	at TRANSFORMER/jei@15.2.0.27/mezz.jei.library.load.PluginLoader.createRecipeManager(PluginLoader.java:144)
	at TRANSFORMER/jei@15.2.0.27/mezz.jei.library.startup.JeiStarter.start(JeiStarter.java:132)
	at TRANSFORMER/jei@15.2.0.27/mezz.jei.forge.startup.StartEventObserver.transitionState(StartEventObserver.java:137)
	at TRANSFORMER/jei@15.2.0.27/mezz.jei.forge.startup.StartEventObserver.onEvent(StartEventObserver.java:100)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.multiplayer.ClientPacketListener.m_5859_(ClientPacketListener.java:1451)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:35)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:11)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1106)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.main.Main.main(Main.java:218)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.1.47/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.1.47/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.1.47/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
```

**Comment by iglee42** [comment]
I know this error , you can ignore it
