### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Syndaryl** [iglee42/CreateCasing#42]
**Describe the bug**
Crash on load with create-1.20.1-0.5.1.e

**To Reproduce**
1. Update Create
2. Launch Minecraft

**Expected behavior**
Minecraft would launch

**Additional context**
Create has adjusted functions related to its creative tab, this is called out in the patch notes. IDK if that will help?

**Comment by iglee42** [comment]
I will need a crash report please

**Comment by Mezryss** [comment]
This specifically crashes with 0.5.1e, while the mod works fine with 0.5.1d. `com.simibubi.create.foundation.data.CreateRegistrate.useCreativeTab` was removed in [6ea0776854c1fe2d9159b6d3c11d609ec155b0b9](https://github.com/Creators-of-Create/Create/commit/6ea0776854c1fe2d9159b6d3c11d609ec155b0b9) in Create. The change appears to have broken a *lot* of Create addon mods.

```
[14:18:52] [modloading-worker-0/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to create mod instance. ModID: createcasing, class fr.iglee42.createcasing.CreateCasing
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.20.1-47.1.3.jar%23532!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.1.3.jar%23531!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames,pl:rei_plugin_compatibilities:B}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames,pl:rei_plugin_compatibilities:B}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
Caused by: java.lang.NoSuchMethodError: 'com.simibubi.create.foundation.data.CreateRegistrate com.simibubi.create.foundation.data.CreateRegistrate.useCreativeTab(net.minecraftforge.registries.RegistryObject)'
	at fr.iglee42.createcasing.registries.ModBlocks.<clinit>(ModBlocks.java:61) ~[CreateCasing-1.20.1-1.4.2.jar%23388!/:1.20.1-1.4.2] {re:classloading,pl:rei_plugin_compatibilities:B}
	at fr.iglee42.createcasing.CreateCasing.<init>(CreateCasing.java:70) ~[CreateCasing-1.20.1-1.4.2.jar%23388!/:1.20.1-1.4.2] {re:classloading,pl:rei_plugin_compatibilities:B}
	... 14 more
```

**Comment by iglee42** [comment]
I will update the mod
