### ISSUE TITLE
[Forge - 1.19.2]: Error log regarding JEI plugin

### ISSUE THREAD

**Issue by SiverDX** [iglee42/CreateCasing#59]
Using the latest version (but it was also happening on the previous version)
(Doesn't cause a crash or any actual problems I think)

```log
[18Oct2023 19:35:20.789] [Render thread/ERROR] [mezz.jei.library.load.PluginCaller/]: Caught an error from mod plugin: class fr.iglee42.createcasing.compat.jei.JEIPlugin createcasing:jei
java.lang.IllegalArgumentException: ItemStack value must not be empty. 1 air minecraft:air
	at mezz.jei.common.util.ErrorUtil.checkNotEmpty(ErrorUtil.java:76) ~[jei-1.19.2-forge-11.6.0.1018.jar%23704!/:11.6.0.1018]
	at mezz.jei.library.plugins.vanilla.ingredients.ItemStackHelper.getUniqueId(ItemStackHelper.java:53) ~[jei-1.19.2-forge-11.6.0.1018.jar%23704!/:11.6.0.1018]
	at mezz.jei.library.plugins.vanilla.ingredients.ItemStackHelper.getUniqueId(ItemStackHelper.java:29) ~[jei-1.19.2-forge-11.6.0.1018.jar%23704!/:11.6.0.1018]
	at mezz.jei.library.ingredients.IngredientSet.lambda$create$0(IngredientSet.java:17) ~[jei-1.19.2-forge-11.6.0.1018.jar%23704!/:11.6.0.1018]
	at mezz.jei.library.ingredients.IngredientSet.remove(IngredientSet.java:38) ~[jei-1.19.2-forge-11.6.0.1018.jar%23704!/:11.6.0.1018]
	at mezz.jei.library.ingredients.IngredientSet.removeAll(IngredientSet.java:50) ~[jei-1.19.2-forge-11.6.0.1018.jar%23704!/:11.6.0.1018]
	at mezz.jei.library.ingredients.IngredientInfo.removeIngredients(IngredientInfo.java:51) ~[jei-1.19.2-forge-11.6.0.1018.jar%23704!/:11.6.0.1018]
	at mezz.jei.library.ingredients.IngredientManager.removeIngredientsAtRuntime(IngredientManager.java:148) ~[jei-1.19.2-forge-11.6.0.1018.jar%23704!/:11.6.0.1018]
	at fr.iglee42.createcasing.compat.jei.JEIPlugin.registerRecipes(JEIPlugin.java:28) ~[CreateCasing-1.19.2-1.5.0.jar%23605!/:1.19.2-1.5.0]
	at mezz.jei.library.load.PluginLoader.lambda$createRecipeManager$10(PluginLoader.java:140) ~[jei-1.19.2-forge-11.6.0.1018.jar%23704!/:11.6.0.1018]
	at mezz.jei.library.load.PluginCaller.redirect$bhk000$callOnPlugins(PluginCaller.java:540) ~[jei-1.19.2-forge-11.6.0.1018.jar%23704!/:11.6.0.1018]
	at mezz.jei.library.load.PluginCaller.callOnPlugins(PluginCaller.java:25) ~[jei-1.19.2-forge-11.6.0.1018.jar%23704!/:11.6.0.1018]
	at mezz.jei.library.load.PluginLoader.createRecipeManager(PluginLoader.java:140) ~[jei-1.19.2-forge-11.6.0.1018.jar%23704!/:11.6.0.1018]
	at mezz.jei.library.startup.JeiStarter.start(JeiStarter.java:114) ~[jei-1.19.2-forge-11.6.0.1018.jar%23704!/:11.6.0.1018]
	at mezz.jei.forge.startup.StartEventObserver.transitionState(StartEventObserver.java:137) ~[jei-1.19.2-forge-11.6.0.1018.jar%23704!/:11.6.0.1018]
	at mezz.jei.forge.startup.StartEventObserver.onEvent(StartEventObserver.java:100) ~[jei-1.19.2-forge-11.6.0.1018.jar%23704!/:11.6.0.1018]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.3.jar%23134!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.3.jar%23134!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%23134!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%23134!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_5859_(ClientPacketListener.java:1321) ~[client-1.19.2-20220805.130853-srg.jar%23889!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:35) ~[client-1.19.2-20220805.130853-srg.jar%23889!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:11) ~[client-1.19.2-20220805.130853-srg.jar%23889!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.19.2-20220805.130853-srg.jar%23889!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.19.2-20220805.130853-srg.jar%23889!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.19.2-20220805.130853-srg.jar%23889!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.19.2-20220805.130853-srg.jar%23889!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[client-1.19.2-20220805.130853-srg.jar%23889!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1072) ~[client-1.19.2-20220805.130853-srg.jar%23889!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23889!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23889!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23889!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.3.0.jar%23150!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%23137!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%23137!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%23137!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%23137!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%23137!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%23137!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%23137!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:58) [ForgeWrapper-1.5.6-prism.jar:1.5.6-prism]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]
```

**Comment by iglee42** [comment]
It's no a big problem I know why this bug produce
