### ISSUE TITLE
[Bug] Game sometimes crashes on startup

### ISSUE THREAD

**Issue by SiverDX** [iglee42/CreateCasing#70]
Version: 1.19.2-1.6.0-ht1
(Heavily modded environment)

```
[10Feb2024 17:51:18.607] [modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: createcasing, class fr.iglee42.createcasing.CreateCasing
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.3.0.jar%23859!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.3.0.jar%23858!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:?]
Caused by: java.lang.ExceptionInInitializerError
	at fr.iglee42.createcasing.registries.ModBlocks.<clinit>(ModBlocks.java:72) ~[CreateCasing-1.19.2-1.6.0-ht1.jar%23588!/:1.19.2-1.6.0-ht1]
	at fr.iglee42.createcasing.CreateCasing.<init>(CreateCasing.java:78) ~[CreateCasing-1.19.2-1.6.0-ht1.jar%23588!/:1.19.2-1.6.0-ht1]
	... 14 more
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap.computeIfAbsent(Unknown Source) ~[?:?]
	at com.jozufozu.flywheel.core.StitchedSprite.<init>(StitchedSprite.java:24) ~[flywheel-forge-1.19.2-0.6.10-20.jar%23942!/:0.6.10-20]
	at com.jozufozu.flywheel.core.StitchedSprite.<init>(StitchedSprite.java:28) ~[flywheel-forge-1.19.2-0.6.10-20.jar%23942!/:0.6.10-20]
	at com.simibubi.create.foundation.block.render.SpriteShiftEntry.set(SpriteShiftEntry.java:13) ~[create-1.19.2-0.5.1.f.jar%23583!/:0.5.1.f]
	at com.simibubi.create.foundation.block.render.SpriteShifter.lambda$get$0(SpriteShifter.java:20) ~[create-1.19.2-0.5.1.f.jar%23583!/:0.5.1.f]
	at net.minecraftforge.fml.DistExecutor.unsafeRunWhenOn(DistExecutor.java:111) ~[fmlcore-1.19.2-43.3.0.jar%23858!/:?]
	at com.simibubi.create.foundation.block.render.SpriteShifter.get(SpriteShifter.java:20) ~[create-1.19.2-0.5.1.f.jar%23583!/:0.5.1.f]
	at com.simibubi.create.AllSpriteShifts.get(AllSpriteShifts.java:124) ~[create-1.19.2-0.5.1.f.jar%23583!/:0.5.1.f]
	at com.simibubi.create.AllSpriteShifts.<clinit>(AllSpriteShifts.java:27) ~[create-1.19.2-0.5.1.f.jar%23583!/:0.5.1.f]
	at fr.iglee42.createcasing.registries.ModBlocks.<clinit>(ModBlocks.java:72) ~[CreateCasing-1.19.2-1.6.0-ht1.jar%23588!/:1.19.2-1.6.0-ht1]
	at fr.iglee42.createcasing.CreateCasing.<init>(CreateCasing.java:78) ~[CreateCasing-1.19.2-1.6.0-ht1.jar%23588!/:1.19.2-1.6.0-ht1]
	... 14 more
```

**Comment by iglee42** [comment]
Hey, I don't really know how to fix the bug.
Is this a really recurring bug or is it occasional ?

**Comment by mbwarn** [comment]
I’m also having this issue, on another version.

For me, it’s seldom and intermittent. No more than a minor annoyance. I just restart and I’m good.
